# -*- coding: utf-8 -*-
"""first.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wqE4DedxQmQ2inV32d-JFzqZQ6lzXfqQ

**Passo a passo da solução do desafio**
"""

#Passo 1 - Percorrer todos os arquivos da pasta base de dados
import os
import pandas as pd


lista_arquivo =  os.listdir('/content/drive/MyDrive/Classroom/Curso básico de Python/Vendas (1)')
display(lista_arquivo)

tabela_total = pd.DataFrame()

#Passo 2 - Importar as bases de dados de vendas

for arquivo in lista_arquivo:
   if "Vendas" in arquivo:
     tabela = pd.read_csv(f"/content/drive/MyDrive/Classroom/Curso básico de Python/Vendas (1)/{arquivo}")
     tabela_total = tabela_total.append(tabela)
display(tabela_total)

#Passo 3- Calcular o produto mais vendido (em quantidade)
tabela_produtos = tabela_total.groupby('Produto').sum()
tabela_produtos = tabela_produtos[['Quantidade Vendida', 'Preco Unitario']].sort_values(by="Quantidade Vendida", ascending=False)
display(tabela_produtos)

#Passo 4 - Calcular o produto que mais faturou (em faturamento)

tabela_total["Faturamento"] = tabela_total["Quantidade Vendida"] * tabela_total["Preco Unitario"]

tabela_faturamento = tabela_total.groupby('Produto').sum()
tabela_faturamento = tabela_faturamento[['Faturamento']].sort_values(by="Faturamento", ascending=False)
display(tabela_faturamento)

#Passo 5 - Calcular a loja/cidade que mais vendeu (em faturamento) - criar um gráfico/dashboard

tabela_lojas = tabela_total.groupby('Loja').sum()
tabela_lojas = tabela_lojas[['Faturamento']]
display(tabela_lojas)

import plotly.express as px

grafico=px.bar(tabela_lojas, x=tabela_lojas.index, y='Faturamento')
grafico.show()